### ISSUE TITLE
Error in isochrones setup

### ISSUE THREAD

**Issue by PNMwaniki** [jvines/astroARIADNE#87]
Hi!

I am following the installation, but I am getting this persistent error in the isochrones setup section.

**(ariadne) pato@pato-HP-EliteBook-820-G4:~$ # This downloads required stellar evolution models
python -c "from isochrones import get_bc_grid; get_bc_grid('mist')"
Holoviews not imported. Some visualizations will not be available.
PyMultiNest not imported.  MultiNest fits will not work.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'get_bc_grid' from 'isochrones' (/home/pato/anaconda3/envs/ariadne/lib/python3.11/site-packages/isochrones/__init__.py)**

How can I fix this, please?

**Comment by cevawm** [comment]
I am having the same exact issue.

**Comment by cevawm** [comment]
After a lot of digging plus looking at the latest PRs in `isochrones`, it appears this instruction for setting up `isochrones` on the `astroARIADNE` README is irrelevant, and perhaps has been for some time.  

What you should actually do is use the alternative set of instructions on the README, i.e. run `nosetests isochrones`, however that is also not going to work since `nosetests` does not work with python 3.11 (the version of python required by `astroARIADNE`).  You should do `pytest isochrones` instead.  

However, `isochrones` itself is not well updated, and does not work well (or even at all) with python 3.11 or higher.   Some recent commits on the `isochrones` github repo seem to address some issues, but more work is needed.  

In the meantime, I made a fork of `isochrones` and went ahead and fixed some issues myself, such that I can now use the latest version of both `astroARIADNE` and `isochrones`, without any problems (so far).

**Comment by jvines** [comment]
@cevawm @PNMwaniki 
Sorry, I thought I had answered this. The current way you can download the isochrones is with `from isochrones import get_ichrone; get_ichrone('mist', bands=['G','BP','RP','J','H','K','W1','W2','W3','TESS','Kepler'])`

FWIW I'm working on a new package for doing BMA with isochrones. We're currently writing up the paper but when it's out, the idea will be to replace isochrones with that new package.
